### ISSUE TITLE
Ability to use clientid and clientsecret

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/credhub-resource#2]
Currently we can only authenticate with a username and password

It would be great if we could authenticate using a client_id and client_secret

**Comment by ramonskie** [comment]
as they changed it in the cli and in the default credhub opsfiles in bosh deployment to `client_id` and `client_secret`
we need to add this and i think it should default to `client_id` as well.

but it seems we do a need a big refactor for this as they changed allot in the code upstream
